# Generated by Django 5.0.4 on 2024-06-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe_to_newsletter',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
