# Generated by Django 5.0.4 on 2024-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servise_name', models.CharField(max_length=120)),
                ('about_service', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
